# contains AWS credentials for the tanzu-prow-bot user
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tanzu-prow-bot
  namespace: test-pods
spec:
  backendType: secretsManager
  # optional: specify role to assume when retrieving the data
  roleArn: arn:aws:iam::605126514283:role/tanzu-prow-secret-manager-role
  # optional: specify region
  region: us-east-1
  dataFrom:
    - tanzu/tanzu-prow-bot

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: prow
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::605126514283:role/tanzu-prow-secret-manager-role
  region: us-east-1
  data:
    - key: tanzu/prow-service-cluster
      name: github-token
    - key: tanzu/prow-service-cluster
      name: appid

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: hmac-token
  namespace: prow
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::605126514283:role/tanzu-prow-secret-manager-role
  region: us-east-1
  data:
    - key: tanzu/prow-service-cluster
      name: hmac-token

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: github-oauth-config
  namespace: prow
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::605126514283:role/tanzu-prow-secret-manager-role
  region: us-east-1
  dataFrom:
    - tanzu/github-oauth-config

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cookie
  namespace: prow
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::605126514283:role/tanzu-prow-secret-manager-role
  region: us-east-1
  dataFrom:
    - tanzu/cookie

---

# gcs-credentials secret is required in both prow as well as test-pods namespace
# refer: https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#configure-a-gcs-bucket

apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gcs-credentials
  namespace: prow
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::605126514283:role/tanzu-prow-secret-manager-role
  region: us-east-1
  dataFrom:
    - tanzu/prow-service-account

---

apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gcs-credentials
  namespace: test-pods
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::605126514283:role/tanzu-prow-secret-manager-role
  region: us-east-1
  dataFrom:
    - tanzu/prow-service-account

      
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: testgrid-gcs-credentials
  namespace: test-pods
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::605126514283:role/tanzu-prow-secret-manager-role
  region: us-east-1
  dataFrom:
    - tanzu/testgrid-service-account
